name: CI for ExaequOS
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  #############################################################################
  ### Linux
  #############################################################################
  build_linux:
    name: Build on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ExaequOS
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install system packages
        run: |
          sudo apt-get update
          python3 -m pip install -r requirements.txt
      - name: Compile ExaequOS
        run: |
          python3 build.py
      - name: Check build
        run: |
          cd ExaequOS
          ls ExaequOS libcef.so

  #############################################################################
  ### Windows
  #############################################################################
  build_windows:
    name: Build on Windows
    runs-on: windows-2022
    steps:
      # Add path for finding cl.exe
      # FIXME: I dunno why Godot editor and godot-cpp can find cl.exe while our
      # godot native modules cannot find it without this extra path
      - uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Checkout ExaequOS
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install system packages
        shell: powershell
        run: |
          python3 -m pip install -r requirements.txt
      - name: Compile ExaequOS
        shell: powershell
        run: |
          python3 build.py
      - name: Check build
        run: |
          Test-Path -Path \a\exa-application\ExaequOS\ExaequOS.exe
          Test-Path -Path \a\exa-application\ExaequOS\libcef.dll
